#37 storyboard
Interacao-Humano-Computador/2020.1-Prefeitura-Municipal-de-Arco-Iris pull request #39
Opened 2020-10-26 20:57 UTC by giovannabbottino

**Descrição da mudança**  
- Criação do storyboard de visualizar a prestação de contas públicas,
- Criação do storyboard de visualizar as notícias recentes sobre a cidade e
- Criação do storyboard de visualizar as informações sobre o Coronavírus na cidade.
- Atualiza sidebar
- Organiza pasta de apresentação

**Issue relacionada**  
FIX #37

2020-10-27 22:00 UTC, Gabrielle-Ribeiro requested changes
Tem que criar uma pasta nova pra colocar as coisas dessa etapa

2020-10-27 22:16 UTC, giovannabbottino commented
> Tem que criar uma pasta nova pra colocar as coisas dessa etapa

Qual nome dar para essa pasta?

2020-10-28 22:16 UTC, AlineLermen approved these changes

2020-10-28 22:18 UTC, Gabrielle-Ribeiro approved these changes

2020-10-28 22:18 UTC, merged